-d D:\Git\TangNano9K_motordriver\sampleProject\StepperMotor\impl\gwsynthesis\StepperMotor.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst D:\Git\TangNano9K_motordriver\sampleProject\StepperMotor\src\top.cst
-cfg D:\Git\TangNano9K_motordriver\sampleProject\StepperMotor\impl\pnr\device.cfg
-gao_crc 0010001111111110
-bit
-tr
-ph
-timing
-cst_error
-rtl_gao
