M48
; DRILL file {KiCad (6.0.11)} date Mon Feb 27 18:44:30 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-27T18:44:30+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X64.4Y-60.9
X64.77Y-142.875
X139.065Y-142.875
X157.226Y-49.784
T0
M30
