M48
; DRILL file {KiCad (6.0.11)} date Wed Feb 22 21:26:40 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-22T21:26:40+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X64.4Y-60.9
X64.77Y-142.875
X139.065Y-142.875
X157.226Y-49.276
T0
M30
