M48
; DRILL file {KiCad (6.0.5)} date Fri Jan 27 21:44:15 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-27T21:44:15+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X64.4Y-60.9
X64.77Y-142.875
X139.065Y-142.875
X157.226Y-49.276
T0
M30
